# Generated by Django 5.0.6 on 2024-05-23 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTelegram',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_from', models.TextField(max_length=1000)),
                ('text_to', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('not_learn', 'NOT LEARN'), ('learn', 'LEARN')], default='not_learn', max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_words', to='api.usertelegram')),
            ],
        ),
    ]
