# Generated by Django 5.0.6 on 2024-05-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertelegram',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
